# Generated by Django 4.2 on 2024-11-13 03:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0008_alter_brandsdetails_title_alter_brandusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.brandsdetails')),
            ],
            options={
                'db_table': 'Restaurant_users',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurants.restaurantusers')),
            ],
            options={
                'db_table': 'User_address',
                'unique_together': {('user', 'location')},
            },
        ),
    ]
