# Generated by Django 4.2 on 2024-09-08 06:51

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsdetails',
            name='logo',
            field=models.FileField(upload_to=admin_dashboard.models.brand_logo_upload_path),
        ),
    ]
