# Generated by Django 4.2 on 2024-11-10 21:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_brandaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandaddress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
