# Generated by Django 4.2 on 2024-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_brandaddress_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandaddress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brandaddress',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='brandaddress',
            unique_together={('brand', 'address')},
        ),
        migrations.RemoveField(
            model_name='brandaddress',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='brandaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='brandaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='brandaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='brandaddress',
            name='state',
        ),
    ]
