# Generated by Django 4.2 on 2024-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_brandaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsdetails',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='brandusers',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
