# Generated by Django 4.2 on 2024-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_alter_brandsdetails_title_alter_brandusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandusers',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
    ]
